"""KMRL Malayalam ⇄ English domain glossary and transliteration tables.

This powers the offline translation fallback. It is deliberately domain-heavy:
metro operations, safety, regulatory and administrative vocabulary is exactly
what KMRL circulars are written in, so a targeted glossary recovers far more
meaning than a generic word list would — and it needs no model download, which
keeps the demo working on a laptop with no GPU and no API key.
"""

from __future__ import annotations

# --------------------------------------------------------------------------
# Multi-word phrases are matched before single words, longest first.
# --------------------------------------------------------------------------
MALAYALAM_PHRASES: dict[str, str] = {
    "കൊച്ചി മെട്രോ റെയിൽ ലിമിറ്റഡ്": "Kochi Metro Rail Limited",
    "മെട്രോ റെയിൽ സുരക്ഷാ കമ്മീഷണർ": "Commissioner of Metro Rail Safety",
    "അടിയന്തര ബ്രേക്ക് പരിശോധന": "emergency brake inspection",
    "അടിയന്തര ബ്രേക്ക്": "emergency brake",
    "സുരക്ഷാ പരിശോധന": "safety inspection",
    "സുരക്ഷാ സർക്കുലർ": "safety circular",
    "സുരക്ഷാ ഓഡിറ്റ്": "safety audit",
    "സുരക്ഷാ വിഭാഗം": "Safety department",
    "അപകട റിപ്പോർട്ട്": "incident report",
    "അറ്റകുറ്റപ്പണി റിപ്പോർട്ട്": "maintenance report",
    "പരിശോധനാ റിപ്പോർട്ട്": "inspection report",
    "പ്രവർത്തന വിഭാഗം": "Operations department",
    "റോളിംഗ് സ്റ്റോക്ക്": "Rolling Stock",
    "പ്ലാറ്റ്ഫോം സ്ക്രീൻ ഡോർ": "platform screen door",
    "പർച്ചേസ് ഓർഡർ": "purchase order",
    "ടെൻഡർ അറിയിപ്പ്": "tender notice",
    "ബോർഡ് യോഗം": "board meeting",
    "യോഗ നടപടിക്രമങ്ങൾ": "minutes of the meeting",
    "പരിസ്ഥിതി ആഘാത പഠനം": "environmental impact study",
    "മലിനീകരണ നിയന്ത്രണ ബോർഡ്": "Pollution Control Board",
    "നിയമ വിഭാഗം": "Legal department",
    "മാനവ വിഭവശേഷി": "Human Resources",
    "ധനകാര്യ വിഭാഗം": "Finance department",
    "സംഭരണ വിഭാഗം": "Procurement department",
    "സിഗ്നലിംഗ് സംവിധാനം": "signalling system",
    "വൈദ്യുതി വിഭാഗം": "Electrical department",
    "അടിയന്തര സാഹചര്യം": "emergency situation",
    "ഒഴിപ്പിക്കൽ നടപടിക്രമം": "evacuation procedure",
    "അഗ്നിശമന സംവിധാനം": "fire fighting system",
    "പരിശീലന പരിപാടി": "training programme",
    "നിർദ്ദേശം നൽകുന്നു": "hereby directs",
    "പൂർത്തിയാക്കണം": "must be completed",
    "നടത്തണം": "must be conducted",
    "സമർപ്പിക്കണം": "must be submitted",
    "ഉറപ്പാക്കണം": "must be ensured",
    "പാലിക്കണം": "must be complied with",
    "മുമ്പായി": "before",
    "നിയമ ലംഘനം": "non-compliance",
    "പിഴ ചുമത്തും": "a penalty will be imposed",
    "അടിയന്തരമായി": "immediately",
    "ഉടൻ തന്നെ": "without delay",
    "അവസാന തീയതി": "last date",
    "സമയപരിധി": "deadline",
    "ജോലി കാർഡ്": "job card",
    "സ്പെയർ പാർട്സ്": "spare parts",
    "ബ്രേക്ക് പാഡ്": "brake pad",
    "ട്രാക്ഷൻ മോട്ടോർ": "traction motor",
    "എസ്കലേറ്റർ തകരാർ": "escalator failure",
    "ലിഫ്റ്റ് തകരാർ": "lift failure",
    "യാത്രക്കാരുടെ സുരക്ഷ": "passenger safety",
    "സേവന തടസ്സം": "service disruption",
    "പ്രതിമാസ റിപ്പോർട്ട്": "monthly report",
    "വാർഷിക റിപ്പോർട്ട്": "annual report",
    "അറിയിപ്പ് നൽകുന്നു": "notice is hereby given",
    "എല്ലാ വകുപ്പുകളും": "all departments",
    "ബന്ധപ്പെട്ട വകുപ്പ്": "the concerned department",
    "മേലധികാരി": "senior officer",
    "മുഖ്യ എഞ്ചിനീയർ": "Chief Engineer",
    "ജനറൽ മാനേജർ": "General Manager",
    "മാനേജിംഗ് ഡയറക്ടർ": "Managing Director",
}

MALAYALAM_WORDS: dict[str, str] = {
    # --- metro & rolling stock ---------------------------------------------
    "മെട്രോ": "metro",
    "ട്രെയിൻ": "train",
    "ട്രെയിനുകൾ": "trains",
    "റെയിൽ": "rail",
    "കോച്ച്": "coach",
    "ബ്രേക്ക്": "brake",
    "ബ്രേക്കുകൾ": "brakes",
    "ചക്രം": "wheel",
    "ബോഗി": "bogie",
    "ഡിപ്പോ": "depot",
    "സ്റ്റേഷൻ": "station",
    "സ്റ്റേഷനുകൾ": "stations",
    "പ്ലാറ്റ്ഫോം": "platform",
    "ട്രാക്ക്": "track",
    "എസ്കലേറ്റർ": "escalator",
    "ലിഫ്റ്റ്": "lift",
    "സിഗ്നൽ": "signal",
    "സിഗ്നലിംഗ്": "signalling",
    "വൈദ്യുതി": "electrical power",
    "ട്രാക്ഷൻ": "traction",
    "സബ്‌സ്റ്റേഷൻ": "substation",
    # --- safety --------------------------------------------------------------
    "സുരക്ഷ": "safety",
    "സുരക്ഷാ": "safety",
    "അപകടം": "accident",
    "അപകടസാധ്യത": "risk",
    "അടിയന്തര": "emergency",
    "അടിയന്തിര": "emergency",
    "തീപിടുത്തം": "fire",
    "ഒഴിപ്പിക്കൽ": "evacuation",
    "പരിശോധന": "inspection",
    "പരിശോധിക്കണം": "shall inspect",
    "മുന്നറിയിപ്പ്": "warning",
    "അപായം": "hazard",
    "സംഭവം": "incident",
    # --- process verbs -------------------------------------------------------
    "നടത്തുക": "conduct",
    "പൂർത്തിയാക്കുക": "complete",
    "സമർപ്പിക്കുക": "submit",
    "ഉറപ്പാക്കുക": "ensure",
    "പാലിക്കുക": "comply",
    "അറിയിക്കുക": "inform",
    "നൽകുക": "provide",
    "തയ്യാറാക്കുക": "prepare",
    "അവലോകനം": "review",
    "അംഗീകാരം": "approval",
    "നിർദ്ദേശം": "directive",
    "നിർദ്ദേശങ്ങൾ": "directives",
    "ഉത്തരവ്": "order",
    "സർക്കുലർ": "circular",
    "അറിയിപ്പ്": "notice",
    "റിപ്പോർട്ട്": "report",
    "രേഖ": "document",
    "രേഖകൾ": "documents",
    "ഫയൽ": "file",
    "കത്ത്": "letter",
    "വിഷയം": "subject",
    "പകർപ്പ്": "copy",
    # --- organisation --------------------------------------------------------
    "വകുപ്പ്": "department",
    "വകുപ്പുകൾ": "departments",
    "വിഭാഗം": "division",
    "ജീവനക്കാർ": "employees",
    "ഉദ്യോഗസ്ഥൻ": "officer",
    "ഉദ്യോഗസ്ഥർ": "officers",
    "മേധാവി": "head",
    "കരാറുകാരൻ": "contractor",
    "വിതരണക്കാരൻ": "supplier",
    "കമ്പനി": "company",
    "സർക്കാർ": "government",
    "മന്ത്രാലയം": "ministry",
    "അതോറിറ്റി": "authority",
    "കമ്മീഷണർ": "Commissioner",
    "യോഗം": "meeting",
    "പരിശീലനം": "training",
    "ജീവനക്കാരൻ": "employee",
    # --- commercial ----------------------------------------------------------
    "ഇൻവോയ്സ്": "invoice",
    "ബിൽ": "bill",
    "പണം": "payment",
    "തുക": "amount",
    "രൂപ": "rupees",
    "ബജറ്റ്": "budget",
    "ചെലവ്": "expenditure",
    "കരാർ": "contract",
    "ടെൻഡർ": "tender",
    "വാങ്ങൽ": "purchase",
    "വിതരണം": "supply",
    "ഓഡിറ്റ്": "audit",
    "നികുതി": "tax",
    # --- compliance ----------------------------------------------------------
    "നിയമം": "law",
    "ചട്ടം": "regulation",
    "അനുസരണം": "compliance",
    "ലംഘനം": "violation",
    "പിഴ": "penalty",
    "ബാധ്യത": "liability",
    "കാലാവധി": "validity period",
    "പുതുക്കൽ": "renewal",
    "അപേക്ഷ": "application",
    "അനുമതി": "permission",
    "സാക്ഷ്യപത്രം": "certificate",
    "പരിസ്ഥിതി": "environment",
    "മലിനീകരണം": "pollution",
    # --- time ----------------------------------------------------------------
    "തീയതി": "date",
    "ദിവസം": "day",
    "ദിവസത്തിനുള്ളിൽ": "within days",
    "ആഴ്ച": "week",
    "മാസം": "month",
    "വർഷം": "year",
    "ഇന്ന്": "today",
    "നാളെ": "tomorrow",
    "ഉടൻ": "immediately",
    "മുൻപ്": "before",
    "ശേഷം": "after",
    "വരെ": "until",
    "മുതൽ": "from",
    # --- months --------------------------------------------------------------
    "ജനുവരി": "January",
    "ഫെബ്രുവരി": "February",
    "മാർച്ച്": "March",
    "ഏപ്രിൽ": "April",
    "മെയ്": "May",
    "ജൂൺ": "June",
    "ജൂലൈ": "July",
    "ഓഗസ്റ്റ്": "August",
    "സെപ്റ്റംബർ": "September",
    "ഒക്ടോബർ": "October",
    "നവംബർ": "November",
    "ഡിസംബർ": "December",
    # --- modality & connectives ---------------------------------------------
    "വേണം": "must",
    "ആവശ്യമാണ്": "is required",
    "നിർബന്ധമാണ്": "is mandatory",
    "കഴിയും": "can",
    "ഇല്ല": "not",
    "എല്ലാ": "all",
    "ഓരോ": "each",
    "കൂടാതെ": "in addition",
    "എന്നാൽ": "however",
    "അതിനാൽ": "therefore",
    "സംബന്ധിച്ച്": "regarding",
    "കുറിച്ച്": "about",
    "പ്രകാരം": "as per",
    "ഉൾപ്പെടെ": "including",
    "ഇത്": "this",
    "അത്": "that",
    "ഒപ്പ്": "signature",
    "സ്ഥലം": "place",
    "പേര്": "name",
    "നമ്പർ": "number",
    "പേജ്": "page",
    "ആകെ": "total",
}

# Numerals -----------------------------------------------------------------
MALAYALAM_DIGITS = str.maketrans("൦൧൨൩൪൫൬൭൮൯", "0123456789")

# --------------------------------------------------------------------------
# Transliteration (ISO-15919 flavoured) so names and unknown terms survive
# translation legibly instead of being dropped.
# --------------------------------------------------------------------------
CONSONANTS: dict[str, str] = {
    "ക": "k", "ഖ": "kh", "ഗ": "g", "ഘ": "gh", "ങ": "ng",
    "ച": "ch", "ഛ": "chh", "ജ": "j", "ഝ": "jh", "ഞ": "nj",
    "ട": "t", "ഠ": "th", "ഡ": "d", "ഢ": "dh", "ണ": "n",
    "ത": "th", "ഥ": "thh", "ദ": "d", "ധ": "dh", "ന": "n",
    "പ": "p", "ഫ": "ph", "ബ": "b", "ഭ": "bh", "മ": "m",
    "യ": "y", "ര": "r", "ല": "l", "വ": "v",
    "ശ": "sh", "ഷ": "sh", "സ": "s", "ഹ": "h",
    "ള": "l", "ഴ": "zh", "റ": "r",
}

INDEPENDENT_VOWELS: dict[str, str] = {
    "അ": "a", "ആ": "aa", "ഇ": "i", "ഈ": "ee", "ഉ": "u", "ഊ": "oo",
    "ഋ": "ri", "എ": "e", "ഏ": "e", "ഐ": "ai", "ഒ": "o", "ഓ": "o", "ഔ": "au",
}

VOWEL_SIGNS: dict[str, str] = {
    "ാ": "aa", "ി": "i", "ീ": "ee", "ു": "u", "ൂ": "oo", "ൃ": "ri",
    "െ": "e", "േ": "e", "ൈ": "ai", "ൊ": "o", "ോ": "o", "ൌ": "au", "ൗ": "au",
}

CHILLUS: dict[str, str] = {
    "ൻ": "n", "ർ": "r", "ൽ": "l", "ൾ": "l", "ൺ": "n", "ൿ": "k", "ം": "m", "ഃ": "h",
}

VIRAMA = "്"
ZWNJ = "‌"
ZWJ = "‍"
